version: '3.7'

services:
  board:
    container_name: board
    env_file: ./.env
    restart: unless-stopped
    image: node
    volumes:
      - './:/app:delegated'
    command: /bin/sh -c "npm install; node server.js"
    working_dir: /app
    ports:
      - "7777:7777"
    networks:
      my-network:
        aliases:
          - board-app
    depends_on:
      - database

  database:
    container_name: mongodb
    image: mongo
    restart: always
    volumes:
      - './data:/data/db'
    ports:
      - '27018:27017'
    networks:
      my-network:
        aliases:
          - db

networks:
  my-network:
    driver: bridge