openapi: 3.0.0
info:
  title: Doc Challenge MoodTechnology
  description: Manage User, docs, words
  version: 1.6.0
  x-logo:
    url: "https://static.vecteezy.com/system/resources/previews/008/513/900/non_2x/beer-mugs-illustration-png.png"
    altText: Beer App

tags:

  - name: Product
    description: For managing a product

  - name: Cart
    description: For managing a cart
 



servers:
  - url: "--*TODAVIA NO HAY SERVER DE PROD*--"
    description: The Prod API server
    variables:
      environment:
        default: prod

  - url: "localhost:7020"
    description: The Local API server
    variables:
      environment:
        default: local

paths: {}

components:
  schemas:
    id:
      description: The unique identifier of the item
      type: string
      readOnly: true
      example: d555345345345as67a342a

    password:
      description: The password for the user
      type: string
      example: Uv13qwer67pLkj

    status:
      description: The item status
      type: string
      default: active
      enum:
        - active
        - inactive
      example: active

    dateCreated:
      description: The date of creation
      type: string
      format: date-time
      readOnly: true
      example: 2019-07-12T19:59:51.801Z

    dateModified:
      description: The date of the last modification
      type: string
      format: date-time
      readOnly: true
      example: 2019-07-20T19:59:51.801Z

    dateCreatedDay:
      description: The day of creation
      type: string
      format: date-time
      readOnly: true
      example: 2019-07-12T19:59:51.801Z

    dateModifiedDay:
      description: The day of last modification
      type: string
      format: date-time
      readOnly: true
      example: 2019-07-12T19:59:51.801Z

    userCreated:
      description: The ID of the user who created the item. This refer to the `id` of the **User** Entity of **Janis ID Service**. See [User](/v2/service/id#tag/User).
      type: string
      readOnly: true
      example: 6a1fc1eeb5b68406e0487a10

    userModified:
      description: The ID of the user who last modified the item. This refer to the `id` of the **User** Entity of **Janis ID Service**. See [User](/v2/service/id#tag/User).
      type: string
      readOnly: true
      example: 7e1fc1eeb5b68406e048796

    accountsIds:
      description: The Related Account's IDs. This refer to the `id` of the **Account** Entity. See [Account](/v2/service/commerce#tag/Account).
      type: array
      items:
        type: string
      example:
        - 1a1fc1eeb5b68406e0487a01
        - 1a1fc1eeb5b68406e0487a00

    accountsReferenceIds:
      description: The Related Account's Reference IDs. This refer to the `referenceId` of the **Account** Entity. See [Account](/v2/service/commerce#tag/Account).
      type: array
      items:
        type: string
      example:
        - "account-acc-01"
        - "account-acc-02"
      
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: admin
      description: The middleware admin

  parameters:
    id:
      name: id
      in: path
      schema:
        type: string
        example: d555345345345as67a342a
      required: true
      description: The unique identifier of the item

    skuId:
      name: id
      in: path
      schema:
        type: string
        example: d555345345345as67a368c
      required: true
      description: |
        The SKU ID. This refer to the `id` of the **Sku** Entity. See [Sku](/v2/service/catalog#tag/Sku).

    ListSortDirection:
      name: sortDirection
      in: query
      description: The direction to sort by
      required: false
      schema:
        type: string
        enum:
          - asc
          - desc

    ListPageNumber:
      name: x-janis-page
      in: header
      description: The page to get
      required: false
      schema:
        type: integer
        default: 1
        minimum: 0
        exclusiveMinimum: true

    ListPageSize:
      name: x-janis-page-size
      in: header
      description: The page size to get
      required: false
      schema:
        type: integer
        default: 60
        minimum: 0
        exclusiveMinimum: true

    JanisEntity:
      name: janis-entity
      in: header
      description: The entity name
      required: true
      schema:
        type: string

  headers:
    x-janis-total:
      description: The total amount of records in the list
      schema:
        type: integer
        minimum: 0

  responses:
    GenericSuccess:
      description: Operation succeeded
      content:
        application/json:
          schema:
            type: object
